#!/bin/sh
set -e
# Automatically added by dh_installsystemduser/13.3.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user mask 'pifmrds.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'pifmrds.service' >/dev/null || true
		deb-systemd-helper --user unmask 'pifmrds.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.3.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user mask 'pifmrds.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'pifmrds.service' >/dev/null || true
		deb-systemd-helper --user unmask 'pifmrds.service' >/dev/null || true
	fi
fi
# End automatically added section
